### PR TITLE
Use fstat(), not fseek(), to determine file size

### PR DESCRIPTION
**Pull request by atdt**
Subclause 7.21.9.2 of the C standard stipulates that "a binary stream need not
meaningfully support fseek calls with a whence value of SEEK_END";
Additionally, footnote 268 of subclause 7.21.3 says: "Setting the file position
indicator to end-of-file, as with fseek(file, 0, SEEK_END), has undefined
behavior for a binary stream". On non-POSIX systems, using fseek() to set the
file position indicator to end-of-file is not guaranteed to work. If the
program tries to allocate memory based on the result of fseek() / ftell(), the
amount may be incorrect, leading to a potential vulnerability.

To address this issue, we can simply use the file size provided by fstat(),
instead of fseek() / ftell().

Both the diagnosis and the resolution are supported by recommendation [FIO19-C
of the SEI CERT C Coding Standard.](https://www.securecoding.cert.org/confluence/display/c/FIO19-C.+Do+not+use+fseek%28%29+and+ftell%28%29+to+compute+the+size+of+a+regular+file?src=contextnavpagetreemode)

### CODE REVIEW

**Comment by jibsen** [comment]
It seems a shame to turn otherwise portable code into POSIX only.

I think footnote 268 relates to wide-oriented binary streams, but that doesn't help with 7.21.9.2p3, which doesn't say if the limitation is due to orientation.

**Comment by atdt** [comment]
@jibsen, it's actually already implicitly POSIX-only and not portable, because the code assumes that `fseek()` will behave in a way that is guaranteed by POSIX but which the C standard leaves unspecified. This patch makes the dependency on POSIX explicit, so breakage on non-POSIX systems is evident at compile time and not in production.

**Comment by jibsen** [comment]
I guess one portable option would be to read the file in blocks and append them to a dynamic array (which the file already contains code for)? Then a POSIX version (and possibly a Windows API version) could be behind suitable preprocessor checks.

**Comment by lvandeve** [comment]
Indeed this would break multiplatformness, unistd.h isn't on all systems.

If I find a better multiplatform way of doing it, I'll do it. C has file reading abilities in its standard, it can't be that broken that it does undefined behaviour if the file doesn't exist I hope, right? :)

**Comment by lvandeve** [comment]
Ok I've been reading a bit about it.

As mentioned by @jibsen, the footnote about undefined behaviour is related to wide-oriented streams, so not applicable here. The applicable footnote is "A binary stream need not meaningfully support fseek calls with a whence value of SEEK_END."

Which is not the same as undefined behaviour. If we get a good size, all is fine. If we get a bogus size, there is still no vulnerability afaik: we give the size to fread. From what I can tell of its documentation, fread will handle too large sizes safely. It returns how many bytes it successfully read, and we compare it with that, and only return success if it's equal to the input amount.

I think an example of a file with no meaningful size is /dev/urandom. And it seems to return "0" there when I try. But  PNG images have a meaningful size, and it works on all relevant platforms afaik.

So I think it's fine?

If there is a platform where it does not work on a PNG image file, please let me know. If a relevant platform, a fix or specific code for it can be added.

**Pull request closed without merging**
